import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Artnemis",
};

export default function TermsPage() {
  return (
    <div className="mx-auto flex w-full max-w-3xl flex-1 flex-col gap-6 px-4 py-12 sm:px-6 lg:px-10">
      <h1 className="text-3xl font-semibold tracking-[-0.04em] text-slate-950">Terms of Service</h1>
      <p className="text-sm text-slate-500">Last updated: July 2025</p>

      <div className="prose prose-slate max-w-none space-y-6 text-sm leading-relaxed text-slate-700">
        <section>
          <h2 className="text-lg font-semibold text-slate-950">1. Acceptance</h2>
          <p>
            By accessing or using Artnemis you agree to be bound by these terms. If you do not
            agree, do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-950">2. Description of Service</h2>
          <p>
            Artnemis is an AI-powered exam preparation platform. It provides study module
            management, quiz generation, study plan creation, and collaborative features.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-950">3. User Responsibilities</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>Provide accurate registration information.</li>
            <li>Keep your credentials and API keys confidential.</li>
            <li>Do not upload copyrighted material without authorisation.</li>
            <li>Do not attempt to abuse the AI generation features.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-950">4. Intellectual Property</h2>
          <p>
            Artnemis source code is released under the MIT License. User-generated content
            (modules, quizzes, plans) remains the intellectual property of its creator.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-950">5. AI-Generated Content</h2>
          <p>
            Content generated by AI (quizzes, study plans, topic suggestions) is provided as-is
            for educational purposes. The service makes no guarantee regarding the accuracy or
            completeness of AI-generated material.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-950">6. Limitation of Liability</h2>
          <p>
            The service is provided &quot;as is&quot; without warranties of any kind. In no event shall the
            authors be liable for any damages arising from the use of the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-950">7. Modifications</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use after changes
            constitutes acceptance.
          </p>
        </section>
      </div>
    </div>
  );
}
